title: Automation and Robotics In Reshaping The Workforce
description: A report on disruption innovation in MMS142 (2023) by Group D
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman

github:
  pdf_url: https://github.com/mms142-groupd-2023/mms142-groupd-2023.github.io/blob/51e25682a433a86c756f9b20eb690ee17b72d985/files/docs/Final%20Report%20Content.pdf
